<?php
// views/transactions/index.php

// Include the authentication check and session details
// This page should typically be accessible only by admins
session_start();
if (!isset($_SESSION['user_id']) || !isset($_SESSION['role']) || $_SESSION['role'] !== 'admin') {
    header("Location: ../../login.php"); // Redirect to login if not authenticated as admin
    exit;
}

$user_name = $_SESSION['username'] ?? 'Admin';

// Include database configuration
require_once '../../config/database.php'; // Adjust path as needed
$database = new Database();
$db = $database->getConnection();

$transactions = [];
$error_message = '';

try {
    // Prepare SQL query to fetch all transactions with related user, card, and recharge info
    // Joining with user, card, and recharge tables for more context
    $query = "
        SELECT t.id, t.user_id, u.username as user_username, u.first_name as user_first_name, u.last_name as user_last_name,
               t.card_id, c.balance_credits as card_balance, c.total_credits as card_total, c.c_status as card_status,
               t.t_time, t.t_type,
               t.recharge_id, r.r_time as recharge_time, r.r_type as recharge_type
        FROM transactions t
        LEFT JOIN user u ON t.user_id = u.id
        LEFT JOIN card c ON t.card_id = c.id
        LEFT JOIN recharge r ON t.recharge_id = r.id
        ORDER BY t.t_time DESC
    ";
    $stmt = $db->prepare($query);
    $stmt->execute();

    $transactions = $stmt->fetchAll(PDO::FETCH_ASSOC);
} catch (PDOException $e) {
    // Log the error or handle it appropriately in production
    $error_message = "Could not load transactions. Please try again later.";
    error_log("Transactions index page query error: " . $e->getMessage()); // Log the actual error
}

// Prepare the specific content for this page
$content = "
    <h2>Manage Transactions</h2>
    <p>View and manage financial transactions.</p>
";

// Display error message if query failed
if ($error_message) {
    $content .= "<div class='alert alert-danger' role='alert'>" . htmlspecialchars($error_message) . "</div>";
} else {
    // Add a button to create a new transaction (maybe for admin, or it's auto-generated by recharges/orders?)
    // For now, let's assume transactions are primarily created by other actions (recharges, orders).
    // $content .= "
    // <div class='mb-3'>
    //     <a href='create.php' class='btn btn-success'>Add New Transaction</a>
    // </div>
    // ";

    // Check if transactions exist
    if (!empty($transactions)) {
        $content .= "
        <div class='table-responsive'>
            <table class='table table-striped table-hover'>
                <thead class='table-dark'>
                    <tr>
                        <th>ID</th>
                        <th>User</th>
                        <th>Card ID</th>
                        <th>Card Status</th>
                        <th>Transaction Time</th>
                        <th>Transaction Type</th>
                        <th>Linked Recharge ID</th>
                        <th>Linked Recharge Time</th>
                        <th>Recharge Type</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
        ";

        foreach ($transactions as $transaction) {
            $user_name_display = $transaction['user_first_name'] ? htmlspecialchars($transaction['user_first_name'] . ' ' . $transaction['user_last_name']) : htmlspecialchars($transaction['user_username']);
            $user_link = $transaction['user_id'] ? "<a href='../../views/users/view.php?id=" . $transaction['user_id'] . "'>" . $user_name_display . "</a>" : 'N/A';
            $card_link = $transaction['card_id'] ? "<a href='../../views/cards/view.php?id=" . $transaction['card_id'] . "'>Card #" . $transaction['card_id'] . "</a>" : 'N/A';
            $recharge_link = $transaction['recharge_id'] ? "<a href='../../views/recharge/view.php?id=" . $transaction['recharge_id'] . "'>#" . $transaction['recharge_id'] . "</a>" : 'N/A';

            $content .= "
                    <tr>
                        <td>" . htmlspecialchars($transaction['id']) . "</td>
                        <td>" . $user_link . "</td>
                        <td>" . $card_link . "</td>
                        <td>" . htmlspecialchars($transaction['card_status']) . "</td>
                        <td>" . htmlspecialchars($transaction['t_time']) . "</td>
                        <td>" . htmlspecialchars($transaction['t_type']) . "</td>
                        <td>" . $recharge_link . "</td>
                        <td>" . ($transaction['recharge_time'] ? htmlspecialchars($transaction['recharge_time']) : 'N/A') . "</td>
                        <td>" . ($transaction['recharge_type'] ? htmlspecialchars($transaction['recharge_type']) : 'N/A') . "</td>
                        <td>
                            <a href='view.php?id=" . $transaction['id'] . "' class='btn btn-sm btn-info'>View</a>
                            <!-- Edit transaction might be complex or restricted -->
                            <!-- <a href='edit.php?id=" . $transaction['id'] . "' class='btn btn-sm btn-warning'>Edit</a> -->
                            <a href='delete.php?id=" . $transaction['id'] . "' class='btn btn-sm btn-danger' onclick='return confirm(\"Are you sure you want to delete transaction ID " . $transaction['id'] . "? This action cannot be undone.\")'>Delete</a>
                        </td>
                    </tr>
            ";
        }

        $content .= "
                </tbody>
            </table>
        </div>
        ";
    } else {
        $content .= "<p>No transactions found.</p>";
    }
}

// Include the main layout template
include '../layouts/app.php'; // Adjust path as needed to point to the layout file

?>